spring:
  application:
    name: microservice-event
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/event_service_qualite?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 8084
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}



management:
  endpoints:
    web:
      exposure:
        include: '*'
