spring:
  application:
    name: admin-service
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3307/admin_service?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}



management:
  endpoints:
    web:
      exposure:
        include: '*'
